# African-Centered Education {.unnumbered}

> "Many of us do not know it, but African people have thousands of years of well-recorded deep thought and educational excellence. Teaching and the shaping of character is one of our great strengths. In our worldview, our children are seen as divine gifts of our creator. Our children, their families, and the social and physical environment must be nurtured together. They must be nurtured in a way that is appropriate for a spiritual people, whose aim is to"build for eternity." What a pity that our communities have forgotten our "Jeles" and our "Jegnas," our great master teachers. What a pity that we cannot readily recall the names of our greatest wise men and women. What a pity that we have come to be dependent on the conceptions and the leadership of others, some of whom not only do not have our interests at heart, they may even be our enemies. Some actually seek to control us for their own benefit through the process of mis-education."
>
> \-- Dr. Asa Hilliard

> "We have a school system that is based upon the psychology of White children and White people. We are trying to educate our children in that system; they are bound to fail. The very structure of the educational; system itself is based upon a white model and therefore it has a built-in failure mechanism for us, one way or the other."
>
> \-- Dr. Amos Wilson
